### ISSUE TITLE
prettier can't resolve "module"

### ISSUE THREAD

**Issue by SaadBazaz** [blomqma/next-rest-framework#101]
Hello,
Here's an issue I'm facing in recent release of NRF:
<img width="488" alt="Screenshot 2023-11-12 at 15 17 59" src="https://github.com/blomqma/next-rest-framework/assets/51885228/26042800-65e1-4844-a48a-1cbe6dab10be">

It seems like prettier is importing something which breaks, "module", which results in all my requests failing.

Seems to be happening locally so far.

**Comment by SaadBazaz** [comment]
Once I run 
```
yarn add module
```

I get error for 'stream'. Then I install stream, and I get error for 'constants'

Seems like node isn't being polyfilled correctly

**Comment by SaadBazaz** [comment]
<img width="982" alt="Screenshot 2023-11-12 at 17 22 48" src="https://github.com/blomqma/next-rest-framework/assets/51885228/328dca08-97e0-451e-ab57-260720c2f93b">

**Comment by blomqma** [comment]
Which Node.js version are you encountering this with? Unfortunately Node 18 is the oldest supported Node version currently with Next REST Framework.

**Comment by SaadBazaz** [comment]
Yep, I'm using v20.0.5
That might be the reason. Lemme downgrade to 18 LTS. 

However, we should have support for latest versions, I don't see how that would be a huge issue so far.

**Comment by SaadBazaz** [comment]
Getting this error on Node 18.12.0 (LTS)
<img width="1107" alt="Screenshot 2023-11-13 at 09 46 56" src="https://github.com/blomqma/next-rest-framework/assets/51885228/3a013509-49c0-48e4-a60a-eb4f0003eee4">

Seems similar to the previous one.

**Comment by SaadBazaz** [comment]
The individual routes are working, but this error prevents the /api docs from loading.
<img width="965" alt="Screenshot 2023-11-13 at 11 36 41" src="https://github.com/blomqma/next-rest-framework/assets/51885228/6a7f0502-a2cc-4129-86cf-a31f1c02db48">

**Comment by SaadBazaz** [comment]
> Which Node.js version are you encountering this with? Unfortunately Node 18 is the oldest supported Node version currently with Next REST Framework.

Can you tell me which exact node version it is? Currently using 18.12.0

**Comment by blomqma** [comment]
Haven't yet been able to reproduce this, but I've identified a potential reason/fix for this due to a module resolution issue with prettier. Could you try if this issue is fixed with `v3.4.7`, thanks!

**Comment by SaadBazaz** [comment]
Solved by upgrading Next Rest Framework, downgrading Node to 18, downgrading Next to 13.5.2, clearing node_modules, and deleting lockfile, then installing again.

Also solved by using nodejs runtime instead of edge runtime in some endpoints.
