### ISSUE TITLE
Support query params

### ISSUE THREAD

**Issue by rliang** [blomqma/next-rest-framework#11]
It seems that `input` is only supported for specifying request body schemas. Can it be made to also support query params?

**Comment by blomqma** [comment]
> It seems that `input` is only supported for specifying request body schemas. Can it be made to also support query params?

Hi @rliang, thanks for submitting the issue. Yes, this seems like a valid issue and I think it's trivial to add support for query params. Give me a few days and I'll get back to you.

**Comment by blomqma** [comment]
Hello again. As promised, support to typings query parameters is now added in v0.3.0.

The API for the `input` object is now extended to support typing the query parameters like so:

```
input: {
  ...
  body: z.object({
    name: z.string()
  }),
  query: {
    page: z.number()
  }
}
```

after which the query is typed in your API handler and middleware functions:

```
handler: async ({
  req: {
    body: { ... },
    query: { test } // Strongly typed.
  },
  ...
}) => {
    ...
}
``` 

In addition to validating and typing the request's query parameters, they are also added to the auto-generated OpenAPI spec:

![Screenshot 2023-01-15 at 20 17 28](https://user-images.githubusercontent.com/35772402/212559436-dc596479-aecb-4637-88f4-9e8e931564f3.jpg)

Closing this issue as resolved, please open another issue if something other comes up.
