### ISSUE TITLE
Share data across middlewares

### ISSUE THREAD

**Issue by crummy** [blomqma/next-rest-framework#111]
Hi - thanks for the great project! I'm looking at migrating from `express-zod-api` which lets us share data across middlewares, by returning values from the middleware. Here's how I imagine it looking in `next-rest-framework`:

```
      .middleware((req, res) => {
        return { foo: "bar" }
      })
      .middleware((req, res, options) => {
        return { ...options, fooTwice: options.bar + options.bar}
      })
      .handler((req, res, options) => {
        console.log(options.foo)
        console.log(options.fooTwice)
        res.status(200).json(TODOS);
      })
```

Here's express-zod-api's documentation on it: https://github.com/RobinTail/express-zod-api?tab=readme-ov-file#middlewares

Perhaps it's already possible to do this with next-rest-framework and I'm missing something?

**Comment by blomqma** [comment]
This can be done, but probably requires the amount of maximum middlewares to be set to some reasonable single digit number with the current implementation.

**Comment by blomqma** [comment]
An update on this: `v4.2.0` adds support for chaining up to three middleware together and sharing data between the middlewares in the way described in your example.

**Comment by crummy** [comment]
Thanks so much!
