### ISSUE TITLE
Make Edge compatible

### ISSUE THREAD

**Issue by SaadBazaz** [blomqma/next-rest-framework#115]
Hey,
As always. Superfan.

I want to use NRF as a standard for literally everything I build, but, recently I wanted to use it in an Edge function. Unfortunately, the Vercel Edge comes with some limitations; a lot of underlying Node utilities are not available.

Here's what NRF tries to access, which the Edge does not provide:
<img width="1233" alt="Screenshot 2023-12-21 at 16 27 38" src="https://github.com/blomqma/next-rest-framework/assets/51885228/2e299438-c691-4e32-8482-b33b8b1e7c94">

Can we either:
1) Use Edge-compatible alternatives, or,
2) Have a graceful fallback incase these utilities are not present, or,
3) Have a lighter version of the lib?

**Comment by blomqma** [comment]
That should be doable as the Node.js file system APIs etc. that are not available in edge runtime, should only be needed in development mode and when generating the OpenAPI spec file. Need to come up with some way to split the code in order to achieve this.

**Comment by cmaycumber** [comment]
I'm in the same boat as @SaadBazaz. If there's anything I can do to help I'd love to see edge functions in `next-rest-framework`. It seems like this would be great for our external and internal API's.

**Comment by blomqma** [comment]
> I'm in the same boat as @SaadBazaz. If there's anything I can do to help I'd love to see edge functions in `next-rest-framework`. It seems like this would be great for our external and internal API's.

Well, solving this is not trivial so this is not a typical "good first issue" but all contributions are welcome of course. I believe this requires at least a new way to split the code using a module bundler as well as possibly replacing some of the dependencies with edge-compatible correspondants and I can't promise solving this within a week or two so this will take some time to further investigate from my side.

**Comment by SaadBazaz** [comment]
> > I'm in the same boat as @SaadBazaz. If there's anything I can do to help I'd love to see edge functions in `next-rest-framework`. It seems like this would be great for our external and internal API's.
> 
> Well, solving this is not trivial so this is not a typical "good first issue" but all contributions are welcome of course. I believe this requires at least a new way to split the code using a module bundler as well as possibly replacing some of the dependencies with edge-compatible correspondants and I can't promise solving this within a week or two so this will take some time to further investigate from my side.

Agreed. The code-splitting part can potentially become a maintenance nightmare. We may have to look into dependency injection patterns for this 👀

**Comment by blomqma** [comment]
Giving an update that I'm currently working on this with promising results so far. Hoping to get https://github.com/blomqma/next-rest-framework/pull/119 merged and released within a week or so, there's plenty of things to test and document for the Edge runtime support.

**Comment by blomqma** [comment]
I have now released `v5.0.0` which adds support for Edge runtime, please check the release notes before upgrading: https://github.com/blomqma/next-rest-framework/releases/tag/v5.0.0
