### ISSUE TITLE
fix: Next REST Framework encountered an error: Error: Dynamic server usage: Page couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error

### ISSUE THREAD

**Issue by mr-kelly** [blomqma/next-rest-framework#120]
When I run `next build`,  a error happend, but Next build success:

<img width="993" alt="image" src="https://github.com/blomqma/next-rest-framework/assets/520852/f49351c0-5f44-498e-b5ca-a0239c278790">

Anything I can do with it?

**Comment by blomqma** [comment]
This is a known issue that I was able to reproduce recently, trying to get it fixed ASAP

**Comment by blomqma** [comment]
This should be fixed in `v5.0.0`, could you check if upgrading to that fixes your issue, thanks: https://github.com/blomqma/next-rest-framework/releases/tag/v5.0.0
