### ISSUE TITLE
Og Image for /api

### ISSUE THREAD

**Issue by SaadBazaz** [blomqma/next-rest-framework#124]
Hey,
Would love to configure a cool OG Image alongside the other options:
```typescript
  ...
  docsConfig: {
    logoUrl: '/omni_logo_black.png',
    faviconUrl: '/favicon-32x32.png',
    title: 'Omni API',
    description:
      'This is the backend which serves Omni Tools. For AI backends, please contact info@getomni.app.',
  },
  ...
```

**Comment by blomqma** [comment]
👍🏻 Support for basic custom OG meta tags has now been added in `v5.1.0`. Documented here: https://github.com/blomqma/next-rest-framework/tree/v5.1.0?tab=readme-ov-file#docs-config

**Comment by SaadBazaz** [comment]
🔥 as always.
