### ISSUE TITLE
Unable to generate docs

### ISSUE THREAD

**Issue by nshonda** [blomqma/next-rest-framework#129]
I started a new project and I'm unable to generate the docs, I have default configurations for a next app but I'm getting the following errors:

![Screenshot from 2024-02-19 18-45-10](https://github.com/blomqma/next-rest-framework/assets/2747573/35a00fc3-1549-4cda-9c56-5fd33a7a4b65)

![Screenshot from 2024-02-19 18-45-15](https://github.com/blomqma/next-rest-framework/assets/2747573/1f202113-8b94-4a08-9cd1-f13857485a90)

**Comment by blomqma** [comment]
Does your `tsconfig.json` contain `"skipLibCheck": true` and is your TS config located in the root of your project? Also I recommend you to try a new experimental version `v5.1.4-beta.1` that changes how dependencies of your code are handled by the CLI commands.

**Comment by nshonda** [comment]
here's my `tsconfig.json`, it is located on the root of the project, I've also tried the new experimental version but I'm getting the same errors

![image](https://github.com/blomqma/next-rest-framework/assets/2747573/674dc43d-57df-41a8-a601-df10a645c5a0)


here's my project structure just in case:

![image](https://github.com/blomqma/next-rest-framework/assets/2747573/b09737f5-752f-4fb4-be37-9aac2b01c1b0)

**Comment by blomqma** [comment]
I can't seem to reproduce this, unfortunately. If your code is open source and you have a reproducible example, I could try to debug this further.

**Comment by blomqma** [comment]
@nshonda Hey I noticed you closed the issue as completed, did you manage to resolve your issue?

**Comment by Type1J** [comment]
I have a very similar issue. I'm using `next` 14.1.0 and `next-rest-framework` 3.1.4-beta1.
