### ISSUE TITLE
Unable to generate

### ISSUE THREAD

**Issue by omermecitoglu** [blomqma/next-rest-framework#147]
added the route below 

```typescript
// ./src/app/api/route.ts

import { docsRoute } from "next-rest-framework";

export const { GET } = docsRoute();
```

and tried to run the command

`npx next-rest-framework generate` 

then the result was

```
Compiling endpoints...
Generating OpenAPI spec...
Next REST Framework config not found. Initialize a docs handler to generate the OpenAPI spec.
```

tried with

`"next-rest-framework": "^5.1.11"`

**Comment by blomqma** [comment]
Hello, what Node.js version are you using?

**Comment by omermecitoglu** [comment]
v20.11.0

I played with the code in the same project for few hours. Then I just tried to run the generate command again, just before I was planning to delete the package from the project. And it worked, but I really don't know what did I do, it just worked.

**Comment by wildseansy** [comment]
I have the same problem.  I'm also using nx with pnpm in a mono-repo.  Even after changing into the directory for the application with the `docsRoute` defined, I get this error.

If I specify the `--configPath` I get the following
```
> pnpm next-rest-framework generate --configPath app/api/mobile/v1/route.ts 

A `configPath` parameter with a value of app/api/mobile/v1/route.ts was provided but no Next REST Framework configs were found.
```

Can't seem to figure out how it's trying to find the docsRoute....
