### ISSUE TITLE
Input params validation not returning http status 400

### ISSUE THREAD

**Issue by jameslshannon** [blomqma/next-rest-framework#151]
I'm guessing this is because the Input path params validator is a relatively new addition, but any params validation errors are not currently resulting in an http 400 being returned (resulting in a misleading http 500 error instead). I can see body & query validation returning 400s in the code but not params.

**Comment by blomqma** [comment]
Thanks, support for this is now added in `v6.0.0-beta.2`, path parameters not conforming to the specified Zod schema will now return an error response and the Zod transforms etc. are also supported so that the parsed values can be accessed in the route handler like with query parameters 👍🏻
