### ISSUE TITLE
Warnings emitted during generate/validate using yarn workspaces

### ISSUE THREAD

**Issue by markedwards** [blomqma/next-rest-framework#158]
Running the generate or validate CLI commands in a project using yarn workspaces emits a bunch of noisy warnings like:

```
Compiling endpoints...
▲ [WARNING] "../package.json" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    ../../node_modules/playwright/lib/index.js:59:64:
      59 │ (0, _utils.addInternalStackPrefix)(path.dirname(require.resolve('../package.json')));
```

All of the warnings point to things in the top-level `node_modules`, so I'm guessing this is related to workspaces.

**Comment by blomqma** [comment]
This is most likely the same issue as described in https://github.com/blomqma/next-rest-framework/issues/159, please upgrade to `v6.0.0-beta.4` and let me know if your issue persists.

**Comment by markedwards** [comment]
I don't get the warnings, but `v6.0.0-beta.4` fails to locate the config, which was not a problem with `v6.0.0-beta.2`.
```
$ yarn next-rest-framework generate                                                      
yarn run v1.22.22
$ /bluefish/node_modules/.bin/next-rest-framework generate
Generating OpenAPI spec...
Next REST Framework config not found. Initialize a docs handler to generate the OpenAPI spec.
Done in 0.16s.
```

**Comment by markedwards** [comment]
This was simply a failure to set `NODE_OPTIONS='--import=tsx'`, working now.  Thanks!
