### ISSUE TITLE
Generator Script not providing any error logging

### ISSUE THREAD

**Issue by MilanDeruelle** [blomqma/next-rest-framework#172]
Hey,

after getting the generator to work (see my comments in the other issue) I am now struggeling with the generation.
The provided example does work correctly (using js with node v20) - however as soon as I add any imports of my own files to the example (even just `import x from 'emptyfile'`) the generator finishes with success but generates an empty file.
The route works fine when testing using `next dev`.

My main problem here: next-rest-framework does not provide any error logging or feedback. I guess it has something todo with ES6 and using modules but I'm not provided with any sort of debugging feedback. 

Also, if anyone has an idea why the generator produces an empty file, I'd be happy about some help.

Thank you and best regards!

**Comment by blomqma** [comment]
Thanks, better error handling for generating the routes has been added in `v6.0.3` by https://github.com/blomqma/next-rest-framework/pull/178, hope this is helpful with debugging.
