### ISSUE TITLE
Invalid request body 400 error schema omits error property

### ISSUE THREAD

**Issue by markedwards** [blomqma/next-rest-framework#175]
The generated OpenAPI schema for a 400 error includes only the `message` property, but there is also an `errors` property with a lot of interesting information.  Is there a reason why this property is not included in these generated errors?

Also, is there any way to have the request validation trigger informative logging in Next?

The issue I'm facing is there is a periodic invalid request body.  The error is not logging in the API server, and because the `errors` property is not in the schema its not logged in the generated client either.

**Comment by blomqma** [comment]
Thanks, I have created an improvement for this by including the Zod error schemas for request bodies, query parameters etc. are automatically included in the auto-generated OpenAPI spec when the schemas have been defined for the endpoints: https://github.com/blomqma/next-rest-framework/pull/177 (released in `v6.0.2`).

Fine-grained logging is something that has been asked for several times, I could try to come up with some solution that allows setting different logging levels for logging any validation errors returned by Next REST Framework.

**Comment by markedwards** [comment]
@blomqma Thanks for working on this.  I still only see this in the error schemas:
```
      "ErrorMessage": {
        "type": "object",
        "properties": { "message": { "type": "string" } },
        "additionalProperties": false
      },
```

There is actually also an `"errors"` property in the error responses, with a lot of detail on what was specifically invalidated.  This is the property I'm after.  Is that possible to add?

**Comment by markedwards** [comment]
So just to be clear, I'm using v6.0.2 and there is still no `errors` property.  Can we follow up on this issue?  Should I make a new issue?
