### ISSUE TITLE
Expected Bug : When using bearerAuth

### ISSUE THREAD

**Issue by imdkbj** [blomqma/next-rest-framework#180]
Process getting hanged when calling a swagger api with bearerAuth enabled and passing a token.

This is a bug or i am doing something wrong!

```js
export const { GET } = docsRoute({
  openApiObject: {
    info: {
      title: 'SSO Api',
      version: '0.1.0',
      description: 'SSO auth api.',
      contact: {
        name: 'Deepak',
        email: 'z@y.com'
      }
    },
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        }
      }
    },
    security: {
      bearerAuth: []
    }
  },

  docsConfig: {
    provider: 'swagger-ui',
    title: 'SSO Api',
    description: 'SSO auth api.',
  }
})
```

**Comment by blomqma** [comment]
Do you have further steps to reproduce? I tried with your config without any problems.

**Comment by imdkbj** [comment]
Interesting. I am getting this when sending api request from swagger ui.

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/1ebb26da-0415-4f05-8967-f7f069c74283">

**Comment by blomqma** [comment]
This is either an issue with your API handler returning that 401 response or a bug in SwaggerUI.
