### ISSUE TITLE
TypeError: (0 , import_react.cache) is not a function

### ISSUE THREAD

**Issue by markedwards** [blomqma/next-rest-framework#181]
Getting this error on a bunch of paths, all of which are outside of my `allowedPaths` config.  This started happening with 6.0.3.

```
Error while importing /api/marketer/conversations/{conversationId}/response, skipping path...
TypeError: (0 , import_react.cache) is not a function
If you don't want this path to be part of your generated OpenAPI spec and want to prevent seeing this error in the future, please add /api/marketer/conversations/{conversationId}/response to 'deniedPaths'.
```

Not sure what the error is, but also not sure why these paths are being considered since they are not in `allowedPaths`.

**Comment by markedwards** [comment]
Seems to be mitigated by using `--configPath`.  However, I still end up with a long list of "ignored" paths, which are not in the `allowedPaths`.

**Comment by blomqma** [comment]
> Seems to be mitigated by using `--configPath`. However, I still end up with a long list of "ignored" paths, which are not in the `allowedPaths`.

Thanks. The error you're seeing is coming from the process of finding the correct docs route containing the config to use for building the OpenAPI spec, for which we can silence errors like this, I'll get it fixed 👍🏻

**Comment by blomqma** [comment]
This should be fixed in `v6.0.5`.

**Comment by markedwards** [comment]
Thanks for the quick fix.

Does it make sense to only examine directories that match the `allowedPaths`?  It seems wasteful to look in other places.  Or maybe I misunderstand that feature.

**Comment by markedwards** [comment]
Of course, I'm being stupid.

Thanks.

**Comment by markedwards** [comment]
Running into this again, this time from an import in an API path.  It's happening when some code imports `cache` from react.

Is this expected?  Why does this fail?
