### ISSUE TITLE
Handling of dynamic API routes

### ISSUE THREAD

**Issue by Cajuteq** [blomqma/next-rest-framework#19]
Next allows [dynamic API routes](https://nextjs.org/docs/api-routes/dynamic-api-routes) to be defined like : 
`/api/posts/[postId].js` single path parameter
`/api/[folder]/[file].js` multiple path parameter
`/api/[...path].js` single catch all path parameter
`/api/[[...path]].js` single optional catch all path parameter

currently this behavior is not handled and result in some surprising results, probably due to encoding issues in the path manipulations :
![image](https://user-images.githubusercontent.com/26676532/223780461-9ba6f654-4f06-446d-aaf5-2d95097f8746.png)

![image](https://user-images.githubusercontent.com/26676532/223780541-95b6c128-588e-4320-8f16-8b4c28dfd9a9.png)

The openAPI specs and Swagger handle the situation using curly braces like so (images from a fastAPI python project) : 

![image](https://user-images.githubusercontent.com/26676532/223781097-5db6ab82-ea97-4ec6-b5f6-b48bc4884e5f.png)

![image](https://user-images.githubusercontent.com/26676532/223781270-68becee1-59ad-4765-bb58-a252261bde8a.png)

![image](https://user-images.githubusercontent.com/26676532/223781841-cc47b42a-df1f-4b8a-9034-78518788cbbb.png)

We should be able to improve the mapApiRoutes that currently replace the bracket with curly braces with a more perfectionated handler that creates the appropriate parameters fields in the swagger.

![image](https://user-images.githubusercontent.com/26676532/223782654-31e08262-45b3-4389-acbb-864b062ca27f.png)

**Comment by blomqma** [comment]
Hello, thanks for yet another issue. This has now been addressed in the latest release [v0.4.0](https://github.com/blomqma/next-rest-framework/releases/tag/v0.4.0)
