### ISSUE TITLE
Query parameters input schema causes OpenAPI spec generation to fail

### ISSUE THREAD

**Issue by franzwollang** [blomqma/next-rest-framework#22]
Just want to say first, I really like this library and I hope it grows over time! I've definitely been feeling for a while it's harder than it should be with Next to get Swagger docs.

Description:
It appears that adding a query parameter schema to an endpoint causes the OpenAPI spec generation to fail and log out "Error: Invalid schema." Originally, I just followed the getting started guide and copied over the example endpoint to see if it worked. I got this error and after a bit of poking, I found out the error disappears and everything suddenly seems to works fine if I comment out the query parameter schema.

Reproduction:
Create a fresh repo, install React & Next, install Next Rest Framework, follow the getting started guide and copy over the example endpoint in the docs. Start the Next dev server and attempt to open Swagger in your browser at "/api".

**Comment by blomqma** [comment]
Hello and thanks for reporting this issue. I was indeed able to reproduce it with the instructions you provided and the issue has now been fixed.

Next REST Framework currently supports validating the query paramters with only object schemas (Zod/Yup) and the getting started guide contained a typo where the query parameter validation was not done with a Zod schema but a plain JS object, resulting in the validation error that you described.

The getting started guide now has some minor improvements that addresses this and I will see if the typings could be improved to catch this with a compile time error in the future.
