### ISSUE TITLE
Swagger UI does not pick up overridden `openApiJsonPath`/`openApiYamlPath`

### ISSUE THREAD

**Issue by FelixZY** [blomqma/next-rest-framework#31]
I do this:

```typescript
export const { defineCatchAllHandler, defineEndpoints } = NextRestFramework({
  apiRoutesPath: "src/pages/api/v1",
  exposeOpenApiSpec: true,
  swaggerUiPath: "/api/v1",
  openApiJsonPath: "/api/v1/dansdata.api.json",
  openApiYamlPath: "/api/v1/dansdata.api.yml",
  openApiSpecOverrides: {
    info: {
      title: "Dansdata",
      description: "Hello world",
      version: "v1",
    },
  },
});
```

which results in

![Next REST Framework _ SwaggerUI](https://user-images.githubusercontent.com/2656517/231141329-1ae57d85-4b0f-45a3-83ef-7c704804db4e.jpg)

As can be seen, Swagger UI is looking for the openapi specification in the wrong location.

**Comment by blomqma** [comment]
Thanks for pointing this out. The SwaggerUI code indeed contained a bug that resulting in custom OpenAPI YAML file paths not working. This has now been fixed in the latest [v0.6.0](https://github.com/blomqma/next-rest-framework/releases/tag/v0.6.0) release!
