### ISSUE TITLE
How can I use my own favicon/logo/title/meta tags?

### ISSUE THREAD

**Issue by FelixZY** [blomqma/next-rest-framework#33]
I would like to use this project to create my API documentation site. However, I would like to brand the Swagger UI with my own favicon, page title and logo. I would also like to set custom meta tags for SEO. How can I accomplish this?

**Comment by FelixZY** [comment]
Thank you for the quick resolution!

> I would also like to set custom meta tags for SEO.

I can't see a way to do this in 0.6.0? `description` is added - but what about e.g. `<meta name="robots" content="noindex">` or `og` tags? I think it would be nice if `swaggerUiConfig` (or some other option) supported next's `<Head />` component.

**Comment by FelixZY** [comment]
Also, looking at https://github.com/blomqma/next-rest-framework/commit/3a9d553a0545166926ae773689787c827b68e36d#diff-3d489e4b7a15d540316d3fb0cdaa188c93466956030cf7539b50778fd2e1d752R61, it seems the current logo implementation does not make use of next's image optimizer which would be desirable.

**Comment by blomqma** [comment]
The current way of generating the SwaggerUI is built with completely custom server-side rendering and I believe that using e.g. the next `Head` component or the image optimizer is not trivial. If you would like to implement a fully custom SwaggerUI, one option would be to host the client yourself, using tools like https://github.com/jellydn/next-swagger-doc and pointing the OpenAPI spec to the one generated by Next REST Framework.

For additional meta tags, I think we could add an additional config option for the Swagger UI config, e.g. `extraTags` that would allow injecting any HTML to the generated SwaggerUI.

**Comment by FelixZY** [comment]
I read up a bit on the code after posting my comment and ended up disabling the Swagger UI (I hope 🤔? I passed `swaggerUiPath: undefined` to `NextRestFramework()`), instead opting to create a fully custom next.js page component utilizing `swagger-ui-react`.
