### ISSUE TITLE
`openapi.json` not generated by `next build`

### ISSUE THREAD

**Issue by FelixZY** [blomqma/next-rest-framework#35]
Related to #25 

I would like to use the current commit sha as part of the generated `openapi.json` file. To do this, I thought to do:

```typescript
export const { defineCatchAllHandler, defineEndpoints } = NextRestFramework({
      version: `v0-${process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA?.substring(0, 7)}`,
```

However, since `openapi.json` is generated locally during development, I'm not receiving the production sha, but rather my local development placeholder. I then thought, maybe I can get around this by deleting the `openapi.json` file and having it rebuild when `next build` is executed. However, it seems the `openapi.json` file is not created by `next build`.

I'm thinking there are two solutions to this:
1. `next build` could generate the `openapi.json` file or,
2. the `openapi.json` file could be generated on-demand, potentially via a specific JS function to allow the implementor to decide how to handle cache.

Generating the `openapi.json` file during development, in development builds, and adding the result to one's repo is likely to lead to many unintentional errors - e.g. for people trying to use `process.env.NODE_ENV` - and should be discouraged IMO.

**Comment by blomqma** [comment]
Thanks, I'm actually currently working on a script that allows generating the OpenAPI spec programmatically, e.g. upon running `next build` so you can expect an improvement to this soon ™. I'll keep this thread updated.

**Comment by blomqma** [comment]
Hello @FelixZY , the latest [v0.7.0](https://github.com/blomqma/next-rest-framework/releases/tag/v0.7.0) adds a new binary that can be used to generate the OpenAPI spec programmatically. It also works in Vercel, the example application in this repository now uses it to generate the API spec before running `next build`.
