### ISSUE TITLE
not registering path

### ISSUE THREAD

**Issue by Yakiyo** [blomqma/next-rest-framework#45]
Hi, i just recently started making an api and since its convenient to deploy nextjs projects on vercel, im using nextjs for it. next-rest-framework is honestly very convenient for me. But im running into issues, the framework isnt registering my api paths. All the examples in this repositoy uses `src/pages/api` for the api routes and `src/next-rest-framework/client.ts` for client initialization. in my case my `pages/api` dir is in my prject root and my framework client initialization is in `src/nrf.ts file. My configuration is
```ts
import { NextRestFramework } from 'next-rest-framework';

export const { defineCatchAllHandler, defineEndpoints } = NextRestFramework({
	apiRoutesPath: '/pages/api/',
	openApiJsonPath: '/api/endpoints.json',
	openApiYamlPath: '/api/endpoints.yaml',
	swaggerUiConfig: {
		title: 'memage',
		description: 'An image manipulation api used to create niche meme-istic images',
	},
	openApiSpecOverrides: {
		openapi: '3.0.0',
		info: {
			title: 'memage',
			version: '0.1.0',
			description: 'Image manipulation api to generate meme-ish images',
			license: {
				name: 'MIT',
			},
		},
		externalDocs: {
			description: 'Documentation',
			url: `https://${process.env.VERCEL_URL ?? 'localhost:3000'}/api`,
		},
	},
});
```
Not sure why its not registering the endpoints. 
Im using github codespaces, i thought maybe it might be an issue with compatibility with codespaces, so i tried deploying a preview to vercel too, same issue, no endpoints are shown there too.
![image](https://github.com/blomqma/next-rest-framework/assets/91675932/1cc51fc0-1173-472a-933a-27296c1a5bfb)
i also tried generating the `openapi.json` file thro github actions on every push and adding the commit to the repo, but same issue. So the issue is definitely with my config, not sure wether apiRoutesPath should be relative to the current path or absolute path from the root. Im lost, any help would be appreciated. Thanks in advance.

My repository can be viewed here [https://github.com/Yakiyo/memage](https://github.com/Yakiyo/memage)

**Comment by blomqma** [comment]
Hey, the `apiRoutesPath` defines a relative path to your API routes folder. In your case, it should be `src/pages/api` and not `pages/api`. Does that fix your issue?

**Comment by Yakiyo** [comment]
If its relative to the file, then should it not be `../pages/api` for me? Since my pages/api folder is in project root and so is the src folder. This is how my project structure looks like
![image](https://github.com/blomqma/next-rest-framework/assets/91675932/3e09194d-197f-49f3-a5f5-b7ff271cb73f)
using `../pages/api` creates an error tho
![image](https://github.com/blomqma/next-rest-framework/assets/91675932/be1bedd9-920a-4b6e-b644-d46cb1a6b225)

**Comment by blomqma** [comment]
Sorry for the confusion, I meant that the path should be relative from the project root (i.e. absolute), so your configuration should work as it is, given your project structure. Are you able to reproduce the issue in a local dev environment without using Codespaces?

**Comment by Yakiyo** [comment]
Oh it works when using locally. Weird how it doesnt work on codespaces and/or using github actions, but does in local setup. maybe some weird black happening. anyways at least thats fixed. 
just a quick question. how do i change the icon in my `api/` route and edit the follow links?

![image](https://github.com/blomqma/next-rest-framework/assets/91675932/0d6b8ff3-fac2-45f3-8fb3-d954329428f9)

**Comment by blomqma** [comment]
> Oh it works when using locally. Weird how it doesnt work on codespaces and/or using github actions, but does in local setup. maybe some weird black happening. anyways at least thats fixed. just a quick question. how do i change the icon in my `api/` route and edit the follow links?
> 
> ![image](https://user-images.githubusercontent.com/91675932/239743443-0d6b8ff3-fac2-45f3-8fb3-d954329428f9.png)

For changing the icon etc., the [SwaggerUI config](https://next-rest-framework.vercel.app/docs/getting-started#swaggerui-config) is your friend. For hiding/editing the footer from the default SwaggerUI there are currently no config options for that. Maybe we could consider adding a config option for hiding the footer completely. Also, nothing prevents you from rendering a custom SwaggerUI using the generated OpenAPI spec files with e.g. [next-swagger-doc](https://github.com/jellydn/next-swagger-doc).

**Comment by Yakiyo** [comment]
i see. thanks for the help. ill close the issue. once again thanks for the support.
