### ISSUE TITLE
NextJS App Router support

### ISSUE THREAD

**Issue by mirko314** [blomqma/next-rest-framework#50]
Hello,

First of all; thanks for making this library!
I spent quite some time looking for such a solution and always thought, somebody on this earth surely has also needed to create a well documented API using NextJS.

When running this library in a NextJS App which uses the (new) App Router.
Have you looked into supporting the new app router?

Best
Mirko

**Comment by blomqma** [comment]
Hey, app router support is definitely on the radar and quite crucial for the future of the framework. Haven't taken the time to do that yet as you're the first one requesting it. There's a good chance I'll invest some time for it in the short-term for it and obviously, all pull requests are welcome.  Keeping this issue open for the time being.

**Comment by Cajuteq** [comment]
also interested in that, we might take the time to make the PR

**Comment by blomqma** [comment]
Working on the App Router support on #49 and looking to release those changes soonish.

**Comment by blomqma** [comment]
App Router support is now live with release v1.0.1: https://github.com/blomqma/next-rest-framework/releases/tag/v1.0.1
