### ISSUE TITLE
App Router Issues

### ISSUE THREAD

**Issue by mirko314** [blomqma/next-rest-framework#57]
First of all, thank you for the app router release! 
I made it work with some workarounds around the following issues and I am really looking forward to fully-typed, openapi-specced endpoints!

I've given it a go and two issues came up, which I am not sure how to fix.
Let me know if I should provide them in a different form e.g in separate issues or if I can help in a different way.

1) There are two issues when one tries to run it in an "app-directory" only NextJS project. The following issue seems to be that even if I do not specify the an `apiRoutesPath`, it still searches for the folder and fails if it does not exist:

```
Next REST Framework encountered an error:
Error: ENOENT: no such file or directory, scandir '/[...]/pages/api'
```
Reproduction: Delete the /pages folder in the example project.
Workaround: Just creating an empty folder "fixes" the error.

2) I could not get the framework to work in a NextJS project where I initially did not use the `src` folder. Since it is a greenfield project I am working on, I could simply move to using the src folder.

**Comment by blomqma** [comment]
Hey, thanks for reporting. I indeed produced the error and it has been fixed by https://github.com/blomqma/next-rest-framework/pull/58. The new release [v1.1.0](https://github.com/blomqma/next-rest-framework/releases/tag/v1.1.0) contains the fix where this should be addressed.
