### ISSUE TITLE
Swagger doc is not generated for app directory without being nested in src dir

### ISSUE THREAD

**Issue by octavio-vercetti** [blomqma/next-rest-framework#69]
Hey, nice job with the package!

appDirPath: "app" does not catch routes  appDirPath: "/app" does

I've seen the `appDirPath` hints at an error when using `/` slash in front, but that's the way it works.
I guess you would like to make it catch routes without the slash.

https://github.com/blomqma/next-rest-framework/assets/91890789/9aa89179-4b86-4878-9202-e1c226a90467

**Comment by blomqma** [comment]
Good catch, this is now fixed in latest release [v1.2.3](https://github.com/blomqma/next-rest-framework/releases/tag/v1.2.3). The `appDirPath` and `apiRoutesPath` now support the following formats:
- `app`
- `/app`
- `./app`
