### ISSUE TITLE
Texts are not changing when using `docsConfig` in `defineDocsRoute` function

### ISSUE THREAD

**Issue by momegas** [blomqma/next-rest-framework#83]
This code: 
```
export const GET = defineDocsRoute({
  autoGenerateOpenApiSpec: true,
  docsConfig: {
    title: 'Squaredev API',
    description: 'Squaredev API',
    logoUrl: 'https://squaredev.io/wp-content/uploads/2022/08/Squaredev-B2.png',
  },
});
```
Results in this docs page.
<img width="746" alt="Screenshot 2023-10-17 at 3 42 09 PM" src="https://github.com/blomqma/next-rest-framework/assets/21096981/54f68517-7d03-4974-81e1-43a392614573">

The expected results is that the texts should be changing.

**Comment by blomqma** [comment]
The `docsConfig` values only change the HTML meta tag values of the generated docs frontend. You can override the texts using the `openApiSpecOverrides` config option which changes the generated `openapi.json` spec, so your config should look something like this:
```
export const GET = defineDocsRoute({
  openApiSpecOverrides: {
    info: {
      title:'Squaredev API',
      description: 'Squaredev API',
    }
  },
  docsConfig: {
    title: 'Squaredev API',
    description: 'Squaredev API',
    logoUrl: 'https://squaredev.io/wp-content/uploads/2022/08/Squaredev-B2.png',
  },
});
```
I do admit though that this is a bit confusing, so maybe I could simplify these options a bit.

**Comment by blomqma** [comment]
This should be fixed in the latest release, the docs config options should now take precedence.

**Comment by momegas** [comment]
Yup indeed it is. I spent some time before opening the issue and couldnt find something.
