### ISSUE TITLE
Middleware

### ISSUE THREAD

**Issue by SaadBazaz** [blomqma/next-rest-framework#89]
Obviously the easy path is to go for NextJS middleware.

But maybe we can have a similar concept here? Or some docs on how we can achieve it with the current version of NRF?

The reason why I ask is because of NextAuth. Most projects use that.

**Comment by blomqma** [comment]
Yeah, some kind of middleware logic makes sense, and some of the earlier versions even contained some middleware logic but that wasn't introduced to the latest client API yet. `v3.2.0` adds a [Middleware](https://github.com/blomqma/next-rest-framework#middleware) function that allows executing logic before the request input is validated. Does this resolve your issue?
